### PR TITLE
Added logo.

### PR DESCRIPTION
**Pull request by rygel**
I've added the logo as SVG and PNG.

### CODE REVIEW

**Comment by mhagnumdw** [comment]
The color of the third "P" differs between PNG and SVG images. In PNG it is green and in SVG it is blue.

**Comment by decebals** [comment]
I don't know why but the logo looks bad (the font is not recognized) in readme file

image

In PF4J project (other project where I am a contributor), we use also a font in logo (https://github.com/pf4j/pf4j/pull/162) but the logo looks OK in readme.

Can you take a look please?

**Comment by rygel** [comment]
@mhagnumdw Thank you for spotting this! At one point I mixed up the colors of the second "P"!

@decebals I'll look into embedding the font into the SVG file somehow.

**Comment by rygel** [comment]
@decebals I've updated the logo and used Google Draw to create it. It does not simply link the font, like vectr.com (which I used before). Instead it draws the text directly.

I've also added a version for a favicon.

**Comment by decebals** [comment]
Thanks! Good work!

**Pull request merged**
