### PR TITLE
Make AbstractTemplateEngine#init method final, use lazy instantiation

### PR DESCRIPTION
**Pull request by decebals**
The goal of this PR is to facilitate https://github.com/pippo-java/pippo/pull/590.
I think that now the code looks better and the performance is a little better (using lazy instantiation).

### CODE REVIEW

**Comment by mhagnumdw** [comment]
@decebals , I took a look over and it looks ok. Tomorrow I will test it with my application that uses Freemarker. Then I come back here.

**Comment by mhagnumdw** [comment]
@decebals , please see this comment: https://github.com/pippo-java/pippo/commit/d0793e211ee6820b02ec2d594b56026a5375deed#r61118560-permalink

**Comment by decebals** [comment]
> @decebals , please see this comment: [d0793e2#r61118560-permalink](https://github.com/pippo-java/pippo/commit/d0793e211ee6820b02ec2d594b56026a5375deed#r61118560-permalink)

See https://github.com/pippo-java/pippo/blob/master/pippo-controller-parent/pippo-weld/src/test/java/ro/pippo/weld/ControllerInterceptorTest.java#L95

My idea is to bring each component where is used. Now many components extract dependencies from `Application` and `ControllerApplication`. Probably in the future we can remove `Application` and `ControllerApplication` entirely. It's hard to test some come components because they receive `application`  instance as parameter and you (developer) don't know what this component uses from application.

I recognize that now is a little bit verbose to set a custom `ControllerFactory`. Maybe to add `ControllerHandlerFactory` is too much, and we should put the logic of this component in `ControllerRouteFactory` and to remove it (`ControllerHandlerFactory`).
The good news is that in the future we don't need `pippo-spring`, `pippo-guice` anymore, no need to set a custom `ControllerFactory` to achieve integration with DI containers.

Please feel free to say what you think, because your feedback is important to me.

**Comment by decebals** [comment]
Remove `ControllerHandlerFactory` layer to simplify injection of custom `ControllerFactory` in `DefaultControllerRouteFactory`.

**Comment by mhagnumdw** [comment]
> See https://github.com/pippo-java/pippo/blob/master/pippo-controller-parent/pippo-weld/src/test/java/ro/pippo/weld/ControllerInterceptorTest.java#L95

I did as in the test class above and in my application I got the error stack below:

Error: `declares @Produces("application/json") but there is no registered ContentTypeEngine for that type!`

```exception
Exception in thread "main" ro.pippo.core.PippoRuntimeException: javax.servlet.ServletException: ro.pippo.core.PippoRuntimeException: br.com.myapp.controller.cofre.CofreConsultaNgController::commandSearch declares @Produces("application/json") but there is no registered ContentTypeEngine for that type!
	at ro.pippo.jetty.JettyServer.start(JettyServer.java:84)
	at ro.pippo.core.Pippo.start(Pippo.java:158)
	at br.com.myapp.PippoLauncher.main(PippoLauncher.java:68)
Caused by: javax.servlet.ServletException: ro.pippo.core.PippoRuntimeException: br.com.myapp.controller.cofre.CofreConsultaNgController::commandSearch declares @Produces("application/json") but there is no registered ContentTypeEngine for that type!
	at ro.pippo.core.PippoFilter.init(PippoFilter.java:115)
	at ro.pippo.jetty.websocket.JettyWebSocketFilter.init(JettyWebSocketFilter.java:43)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at ro.pippo.jetty.JettyServer.start(JettyServer.java:81)
	... 2 more
Caused by: ro.pippo.core.PippoRuntimeException: br.com.myapp.controller.cofre.CofreConsultaNgController::commandSearch declares @Produces("application/json") but there is no registered ContentTypeEngine for that type!
	at ro.pippo.controller.ControllerHandler.validateProduces(ControllerHandler.java:313)
	at ro.pippo.controller.ControllerHandler.<init>(ControllerHandler.java:86)
	at ro.pippo.controller.DefaultControllerHandlerFactory.createRouteHandler(DefaultControllerHandlerFactory.java:37)
	at ro.pippo.controller.DefaultControllerRouteFactory.createRoute(DefaultControllerRouteFactory.java:41)
	at ro.pippo.controller.ControllerRegistry.createControllerRoutes(ControllerRegistry.java:231)
	at ro.pippo.controller.ControllerRegistry.registerControllerMethods(ControllerRegistry.java:169)
	at ro.pippo.controller.ControllerRegistry.register(ControllerRegistry.java:129)
	at ro.pippo.controller.ControllerRegistry.register(ControllerRegistry.java:95)
	at ro.pippo.controller.ControllerApplication.addControllers(ControllerApplication.java:104)
	at br.com.myapp.handlers.init.LoadApi.handle(LoadApi.java:130)
	at br.com.myapp.handlers.init.LevelHandler.handle(LevelHandler.java:46)
	at br.com.myapp.PippoApplication.onInit(PippoApplication.java:82)
	at ro.pippo.core.Application.init(Application.java:114)
	at ro.pippo.core.route.RouteDispatcher.init(RouteDispatcher.java:71)
	at ro.pippo.core.PippoFilter.init(PippoFilter.java:108)
	... 20 more
```

So I needed to set the `ContentTypeEngines` in `DefaultControllerHandlerFactory`. That's right? Thus:

```java
public class PippoApplication extends ControllerApplication {
    @Override
    protected void onInit() {
        ControllerFactory controllerFactory = new GuiceControllerFactory(injector);
        ControllerHandlerFactory controllerHandlerFactory = new DefaultControllerHandlerFactory()
            .setControllerFactory(controllerFactory)
            .setContentTypeEngines(application.getContentTypeEngines()) // <<< I had to define here
            ;
        ControllerRouteFactory controllerRouteFactory = new DefaultControllerRouteFactory()
            .setControllerHandlerFactory(controllerHandlerFactory)
            ;
        setControllerRouteFactory(controllerRouteFactory);
    }
}
```

If I don't set the engines in the `DefaultControllerHandlerFactory`, it will instantiate an empty `ContentTypeEngines` in the `getContentTypeEngines()` method.

**Comment by mhagnumdw** [comment]
> Remove `ControllerHandlerFactory` layer to simplify injection of custom `ControllerFactory` in `DefaultControllerRouteFactory`.

oops, I'll check this change...

**Comment by mhagnumdw** [comment]
@decebals , the observation I made above https://github.com/pippo-java/pippo/pull/591#issuecomment-982922318 is still valid.

It was necessary to set: `.setContentTypeEngines(getContentTypeEngines())`. That's right?

```java
ControllerFactory controllerFactory = new GuiceControllerFactory(injector);
ControllerRouteFactory controllerRouteFactory = new DefaultControllerRouteFactory()
    .setControllerFactory(controllerFactory)
    .setContentTypeEngines(getContentTypeEngines()) // <<< I had to define here - getting from Application
    ;
setControllerRouteFactory(controllerRouteFactory);
```

**Comment by decebals** [comment]
> It was necessary to set: `.setContentTypeEngines(getContentTypeEngines())`. That's right?

Yes. We will see in the future if we can improve this.

**Comment by decebals** [comment]
From what I see, we don't need `ro.pippo.core.ContentTypeEngine#init(Application)`.  Nothing happens there (less in the Gson based implementation but I think that we can move the creation of Gson in a lazy getter method).
I will come with a new PR with this improvement related to `ContentTypeEngine` but for the moment I want to be sure that we don't damage something in what exists already. So, check and close each PR, one by one, to isolate possible regressions.  

By the way, the new release will be `2.0.0` because we will modify/improve substantial some things (break of API).

**Comment by mhagnumdw** [comment]
Well... these changes worked in my application with the modifications I mentioned earlier. I will then approve this PR.

**Comment by decebals** [comment]
> Well... these changes worked in my application with the modifications I mentioned earlier. I will then approve this PR.

I don't understand.  Is it works and I can merge it or do you need more time for a test?

**Pull request merged**
